# The URL the site will be built for
base_url = "https://nilsiker.github.io"

theme = "tabi"
title = "nilsiker"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags", feed = true }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
default_theme = "dark"
skin = "rusty"
favicon_emoji = "🦀"
social_media_card = "/img/profile.png"
socials = [
    { name = "github", url = "https://github.com/nilsiker/", icon = "github" },
    { name = "instagram", url = "https://instagram.com/nilsiker", icon = "instagram" },
    { name = "twitter", url = "https://twitter.com/nilsiker", icon = "twitter" },
]

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
]

allowed_domains = [
    { directive = "font-src", domains = [
        "'self'",
        "data:",
    ] },
    { directive = "img-src", domains = [
        "'self'",
        "https://*",
        "data:",
    ] },
    { directive = "script-src", domains = [
        "'self'",
        "https://cdn.jsdelivr.net",
        "'unsafe-inline'",
        "'unsafe-eval'",
    ] },
    { directive = "style-src", domains = [
        "'self'",
        "https://cdn.jsdelivr.net",
        "'unsafe-inline'",
        "'unsafe-eval'",
    ] },
    { directive = "frame-src", domains = [
        "https://www.youtube-nocookie.com",
    ] },
]
